Replace libc.so/libdl.so/libm.so with ones containing only stubs
Otherwise libc.so in prebuilts/ndk may depends on libdl.so not yet built,
and ld.bfd goes crazy about it with error message reads:

  .../aarch64-linux-android/bin/ld: warning: libdl.so, needed by
    prebuilts/ndk/current/platforms/android-14/arch-arm64/usr/lib/libc.so,
    not found (try using -rpath or -rpath-link)

  prebuilts/ndk/current/platforms/android-14/arch-arm64/usr/lib/libc.so: undefined reference to `dlerror'
  prebuilts/ndk/current/platforms/android-14/arch-arm64/usr/lib/libc.so: undefined reference to `dladdr'
  prebuilts/ndk/current/platforms/android-14/arch-arm64/usr/lib/libc.so: undefined reference to `dlclose'
  prebuilts/ndk/current/platforms/android-14/arch-arm64/usr/lib/libc.so: undefined reference to `dl_iterate_phdr'
  prebuilts/ndk/current/platforms/android-14/arch-arm64/usr/lib/libc.so: undefined reference to `dlopen'
  prebuilts/ndk/current/platforms/android-14/arch-arm64/usr/lib/libc.so: undefined reference to `dlsym'

Change-Id: Ib117746fc4de1709412922f5f7df8f357315542c