Switch prebuilts/ndk "current" from r8 to r9
Also symlink sources/cxx-stl/{gabi++,stlport} to the ones in
8/ (which stay at r8c before exception handling is added).  This is
temporary workaround due to

1. Some projects compile with prebuilts/ndk but link with platform's old
   stlport, causing error reads:
     prebuilts/ndk/current/sources/cxx-stl/stlport/stlport/stl/_ostream.h:187:
       error: undefined reference to 'std::uncaught_exception()'
2. Some projects don't have -ldl when link with stlport in prebuilts/ndk
   which now uses dlopen
3. Some [vendor] binaries linked with platform's stlport may run erratically
   when used in unbundled apps which link with new stlport

Change-Id: Icb7c56a69ceac860636f1c4d0abe98369bbf1c19